import React, {FormEventHandler, SetStateAction} from "react";

export interface ContactState {
    uuid: string;
    firstName: string;
    lastName: string;
    phoneNo: string;
    email: string;
    active: boolean;
}

export interface ContactViewModel {
    contact: ContactState;
    active: boolean;
    formStatus: FormStatus;
}

export const enum FormStatus {
    Editing = "EDITING",
    Pending = "PENDING",
    Ok = "OK",
    Failed = "FAILED"
}

export const enum ContactBlockActions {
    SetContacts = 'SET_CONTACTS',
    SetLoading = 'SET_LOADING',
    SetAll = 'SET_ALL',
}

export interface ReducerAction {
    type: string;
    payload: any;
}

export const genericSubmitForm = (
    url: string,
    fields: string[],
    responseData: any,
    setStateData: React.Dispatch<SetStateAction<any>>,
    accessToken: string,
    dispatch: React.Dispatch<any>,
): [FormEventHandler, string, []] => {

    // NB: While id is autogenerated number - it cannot create a new record, for that it would have to drop uuid
    // so that it was autogenerated
    const fetchData = async (formData: any) => {
        // @ts-ignore
        dispatch({type: FormStatus.Pending.toString(), payload: null});

        try {
            const response = await fetch(url, {
                method: "POST",
                headers: {
                    Accept: "*",
                    "Access-Control-Allow-Origin": "*",
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${accessToken}`
                },
                body: JSON.stringify(formData)
            });

            const data = await response.json();

            setStateData(data);
            // @ts-ignore
            dispatch({type: FormStatus.Ok.toString(), payload: null});
        } catch (err: any) {
            setStateData(err);
            // @ts-ignore
            dispatch({type: FormStatus.Failed.toString(), payload: null});
        }
    };

    const onSubmit = (e: any) => {
        e.preventDefault();


        const formData = fields.reduce((formData, field) => ({
            ...formData,
            [field]: e.target[field].value,
        }), {});
        fetchData(formData);
    }

    // @ts-ignore
    return [onSubmit, status, responseData];
};