version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./monitoring/rules.yml:/etc/prometheus/rules.yml"
    networks:
      - demo
    ports:
      - "9090:9090"
#TODO add alertmanager and grafana
#  alertmanager:
#   grafana:
#    image: grafana/grafana:9.5.2
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    restart: unless-stopped
#    volumes:
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#  TODO: it doesn't refresh the image, it has to be removed and only then replaced; swap it out for tag and version
  backend:
    build: ./spring-backend/.
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - demo
    ports:
      - "8080:8080"
      - "8071:8071"
  frontend:
    build: ./react-front/.
    networks:
      - demo
    ports:
      - "3000:3000"

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - keycloak_backup:/opt/keycloak/data
    ports:
      - "8061:8080"
    command:
      - 'start-dev'

networks:
  demo:
    driver: bridge
volumes:
  keycloak_backup: