apiVersion: v1
kind: Pod
metadata:
  name: frontend-service-pod
  namespace: default
  labels:
    app: frontend-service
    tier: frontend
  annotations:
    description: "This pod runs a simple web application"
spec:
  containers:
    - name: frontend-service
      image: .
      ports:
        - containerPort: 3000
      resources:
      limits:
        memory: "1024MiB"
        cpu: "2"
      requests:
        memory: "512MiB"
        cpu: "1"
      livenessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 3000
        initialDelaySeconds: 3
        periodSeconds: 2
        failureThreshold: 5
  restartPolicy: OnFailure
