global:
  scrape_interval: 60s
  evaluation_interval: 60s

#TODO add alertmanager config and uncomment
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
##          default alertmanager port
#           - alertmanager:9093

rule_files:
 - "rules.yml"

scrape_configs:
  #  - add a config for frontend; conundrum as to what system to chose
  - job_name: "contacts"
    metrics_path: /actuator/prometheus
    # scheme defaults to 'http'
    static_configs:
      # by default - go to host gateway; if run outside of the container - use localhost:8071 instead
      - targets: [ "172.17.0.1:8071" ]
        labels:
          app: "contacts"
  # should use mTLS
  - job_name: "keycloak"
    metrics_path: /metrics
    # scheme defaults to 'http'
    static_configs:
      # by default - go to host gateway; if run outside of the container - use localhost:9100 instead
      - targets: [ "172.17.0.1:9100" ]
        labels:
          app: "keycloak"
#  TODO: add postgres