apiVersion: v1
kind: Pod
metadata:
  name: email-service-pod
  namespace: default
  labels:
    app: email-service
    tier: backend
  annotations:
    description: "This pod runs a simple web application"
spec:
  containers:
    - name: email-service
      image: .
      ports:
        - containerPort: 8040
        - containerPort: 8041
      resources:
      limits:
        memory: "1024MiB"
        cpu: "2"
      requests:
        memory: "512MiB"
        cpu: "1"
      #      volumeMounts:
      #      - name: shared-data
      #        mountPath: /usr/share/nginx/html
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: 8041
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /actuator/health
          port: 8041
        initialDelaySeconds: 3
        periodSeconds: 2
        failureThreshold: 5
  restartPolicy: OnFailure
