apiVersion: v1
kind: Pod
metadata:
  name: authz-service-pod
  namespace: default
  labels:
    app: authz-service
    tier: backend
  annotations:
    description: "This pod runs a simple web application"
spec:
  containers:
    - name: authz-service
      image: .
      ports:
        - containerPort: 8020
        - containerPort: 9010
      resources:
      limits:
        memory: "1024MiB"
        cpu: "2"
      requests:
        memory: "512MiB"
        cpu: "1"
      livenessProbe:
        httpGet:
          path: /metrics
          port: 9010
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /metrics
          port: 9010
        initialDelaySeconds: 3
        periodSeconds: 2
        failureThreshold: 5
  restartPolicy: OnFailure
