management:
  defaults:
    metrics:
      export:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "prometheus"]
  server:
    port: 8071

  #    TODO: reconfigure when they return specific values as per k8s guide
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spreact
    #    TODO: ideally injected by CD pipeline like any other secret
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: spreact
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8020/realms/spreact
  threads:
    virtual:
      enabled: true

#TODO: technically speaking unnecessary as connection is generated automatically with def values
#driverClassName: org:h2:Driver
#url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
#username: admin
#password: admin1


#  spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#  spring.datasource.username=myuser
#  spring.datasource.password=mypassword
#  spring.datasource.driver-class-name=org.postgresql.Driver # Spring Boot can infer this from the URL
#
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect